USE Master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE Name='Create_table')
DROP DATABASE Create_table
GO
CREATE DATABASE Create_table
GO
USE Create_table
GO

-- create table
CREATE TABLE Customers(
	CustomerID INT IDENTITY (1,1) PRIMARY KEY,
	CustomerName VARCHAR (50) NOT NULL,
	ContactName VARCHAR (25) NOT NULL,
	CustomerAddress VARCHAR (255) NOT NULL,
	City VARCHAR (50) NOT NULL,
	PostalCode VARCHAR (50),
	Country VARCHAR (25) NOT NULL
);

CREATE TABLE Categories(
	CategoryID INT IDENTITY(1,1) PRIMARY KEY,
	CategoryName VARCHAR(50) NOT NULL,
	Description VARCHAR(255)
);

CREATE TABLE Employees(
	EmployeeID INT IDENTITY(1,1) PRIMARY KEY,
	LastName VARCHAR(50) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	BirthDate Date NOT NULL,
	Photo NVARCHAR,
	Note VARCHAR(255)
);


CREATE TABLE Shippers (
	ShipperID INT IDENTITY(1,1) PRIMARY KEY,
	ShipperName VARCHAR NOT NULL,
	Phone INT NOT NULL
);

CREATE TABLE Orders(
	OrderID INT IDENTITY(10248,10249) PRIMARY KEY,
	CustomerID INT NOT NULL,
	EmployeeID INT NOT NULL,
	OrderDate Date NOT NULL,
	ShipperID INT NOT NULL
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ShipperID)  REFERENCES Shippers (ShipperID)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Suppliers (
	SupplierID INT IDENTITY(1,1) PRIMARY KEY,
	SupplierName VARCHAR Not Null,
	ContactName VARCHAR Not Null,
	Address VARCHAR Not Null,
	City VARCHAR Not Null,
	PostalCode VARCHAR,
	Country VARCHAR,
	Phone VARCHAR Not Null
);


CREATE TABLE Products(
	ProductID INT IDENTITY(1,1) PRIMARY KEY,
	ProductName VARCHAR(50) NOT NULL,
	SupplierID INT NOT NULL,
	CategoryID INT NOT NULL,
	Unit VARCHAR NOT NULL,
	Price INT
	FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OrderDetails (
	OrderDetailID INT IDENTITY(1,1) PRIMARY KEY,
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL
	FOREIGN KEY (OrderID)   REFERENCES Orders  (OrderID)   ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE ON UPDATE CASCADE
);

