USE Master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE name='CitySoftware' )
DROP DATABASE CitySoftware
CREATE DATABASE CitySoftware
GO
USE CitySoftware
GO

CREATE SCHEMA Groups;
GO

CREATE TABLE Employee(
	EmployeeID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Tel CHAR(11) NOT NULL,
	Email VARCHAR(30),
);

CREATE TABLE Project(
	ProjectID INT IDENTITY(1,1) PRIMARY KEY,
	ProjectName VARCHAR(30) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	Period INT NOT NULL,
	Cost MONEY NOT NULL
);

CREATE TABLE Groups.Group1(
	GroupID INT IDENTITY(1,1) PRIMARY KEY,
	GroupName VARCHAR(30) NOT NULL,
	LeaderID INT,
	ProjectID INT,
	FOREIGN KEY (LeaderID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Groups.GroupDetail(
	GroupID INT,
	EmployeeID INT,
	Status CHAR(20),
	FOREIGN KEY (GroupID) REFERENCES Groups.Group1(GroupID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION
);