USE Master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE Name='DMLexercise')
DROP DATABASE DMLexercise
GO
CREATE DATABASE DMLexercise
GO
USE DMLexercise
GO

CREATE SCHEMA courses;
GO

CREATE TABLE student (
	s_id INT IDENTITY(12345,23456) PRIMARY KEY,
	s_fname VARCHAR(20) NOT NULL,
	s_lname VARCHAR(20) NOT NULL
);

CREATE TABLE courses.course (
	c_id INT PRIMARY KEY,
	c_name VARCHAR(30)
);

CREATE TABLE courses.course_grades(
	cg_id INT PRIMARY KEY,
	semester CHAR(4) NOT NULL,
	c_id INT NOT NULL,
	s_id INT NOT NULL,
	grade CHAR(2) NOT NULL,
	FOREIGN KEY (c_id) REFERENCES courses.course (c_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (s_id) REFERENCES student (s_id) ON DELETE CASCADE ON UPDATE CASCADE
);
